// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spellbox.Contexts;

#nullable disable

namespace Spellbox.Migrations.CardMarketDb
{
    [DbContext(typeof(CardMarketDbContext))]
    [Migration("20260124123720_RemoveGuidId")]
    partial class RemoveGuidId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4");

            modelBuilder.Entity("Spellbox.Model.CardMarketPriceCache", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PriceAverage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PriceFoilLow")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PriceFoilTrend")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PriceLow")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PriceTrend")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("PriceCaches");
                });

            modelBuilder.Entity("Spellbox.Services.PricingSyncState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SyncStates");
                });
#pragma warning restore 612, 618
        }
    }
}
