// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spellbox.Contexts;

#nullable disable

namespace Spellbox.Migrations.CardMarketDb
{
    [DbContext(typeof(CardMarketDbContext))]
    [Migration("20260121145745_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4");

            modelBuilder.Entity("Spellbox.Model.CardMarketPriceCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceAverage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PriceFoilLow")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PriceFoilTrend")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PriceLow")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PriceTrend")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("PriceCaches");
                });

            modelBuilder.Entity("Spellbox.Model.CardMarketProductMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CardVariantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Finish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("CardVariantId", "Finish", "Language")
                        .IsUnique();

                    b.ToTable("ProductMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
