// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spellbox.Contexts;

#nullable disable

namespace Spellbox.Migrations.CardMarketDb
{
    [DbContext(typeof(CardMarketDbContext))]
    [Migration("20260317140611_AddedProductIds")]
    partial class AddedProductIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4");

            modelBuilder.Entity("Spellbox.Model.CardMarketPriceCache", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Avg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("FoilAvg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("FoilLow")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("FoilTrend")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Trend")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProductId");

                    b.ToTable("PriceCaches");
                });

            modelBuilder.Entity("Spellbox.Model.CardMarketProductId", b =>
                {
                    b.Property<Guid>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VariantId");

                    b.ToTable("AddedProductIds");
                });

            modelBuilder.Entity("Spellbox.Services.PricingSyncState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SyncStates");
                });
#pragma warning restore 612, 618
        }
    }
}
