// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spellbox.Model;

#nullable disable

namespace Spellbox.Migrations.CollectionDb
{
    [DbContext(typeof(CollectionDbContext))]
    [Migration("20240728201508_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4");

            modelBuilder.Entity("Spellbox.Model.CollectionBinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Binders");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectionBinderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectionSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectionSnapshotId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectionSnapshotId2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectionSnapshotId3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectionSnapshotId4")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollectionBinderId");

                    b.HasIndex("CollectionSnapshotId");

                    b.HasIndex("CollectionSnapshotId1");

                    b.HasIndex("CollectionSnapshotId2");

                    b.HasIndex("CollectionSnapshotId3");

                    b.HasIndex("CollectionSnapshotId4");

                    b.ToTable("CollectionCard");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionDeck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectionDeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionDeckId");

                    b.ToTable("CollectionSnapshot");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionCard", b =>
                {
                    b.HasOne("Spellbox.Model.CollectionBinder", null)
                        .WithMany("Cards")
                        .HasForeignKey("CollectionBinderId");

                    b.HasOne("Spellbox.Model.CollectionSnapshot", null)
                        .WithMany("Commanders")
                        .HasForeignKey("CollectionSnapshotId");

                    b.HasOne("Spellbox.Model.CollectionSnapshot", null)
                        .WithMany("Companions")
                        .HasForeignKey("CollectionSnapshotId1");

                    b.HasOne("Spellbox.Model.CollectionSnapshot", null)
                        .WithMany("Mainboard")
                        .HasForeignKey("CollectionSnapshotId2");

                    b.HasOne("Spellbox.Model.CollectionSnapshot", null)
                        .WithMany("Maybeboard")
                        .HasForeignKey("CollectionSnapshotId3");

                    b.HasOne("Spellbox.Model.CollectionSnapshot", null)
                        .WithMany("Sideboard")
                        .HasForeignKey("CollectionSnapshotId4");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionSnapshot", b =>
                {
                    b.HasOne("Spellbox.Model.CollectionDeck", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("CollectionDeckId");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionBinder", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionDeck", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionSnapshot", b =>
                {
                    b.Navigation("Commanders");

                    b.Navigation("Companions");

                    b.Navigation("Mainboard");

                    b.Navigation("Maybeboard");

                    b.Navigation("Sideboard");
                });
#pragma warning restore 612, 618
        }
    }
}
