// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spellbox.Model;

#nullable disable

namespace Spellbox.Migrations.CollectionDb
{
    [DbContext(typeof(CollectionDbContext))]
    [Migration("20260105165152_202601051751")]
    partial class _202601051751
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4");

            modelBuilder.Entity("Spellbox.Model.CollectionAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AllocationIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("BinderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CollectionBinderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionCardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BinderId");

                    b.HasIndex("CollectionBinderId");

                    b.HasIndex("CollectionCardId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Allocations", t =>
                        {
                            t.HasCheckConstraint("CK_CollectionAllocation_AllocationIndex", "\n                (\n                    (AllocationIndex = 0 AND BinderId IS NULL AND SnapshotId IS NULL) OR\n                    (AllocationIndex = 1 AND BinderId IS NOT NULL AND SnapshotId IS NULL) OR\n                    (AllocationIndex = 2 AND BinderId IS NULL AND SnapshotId IS NOT NULL)\n                )\n                ");
                        });
                });

            modelBuilder.Entity("Spellbox.Model.CollectionBinder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Binders");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Altered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Finish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Signed")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OracleId", "VariantId")
                        .IsUnique();

                    b.ToTable("CollectionCards");
                });

            modelBuilder.Entity("Spellbox.Model.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Spellbox.Model.DeckCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId", "OracleId", "VariantId")
                        .IsUnique();

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("Spellbox.Model.DeckSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeckId")
                        .IsUnique()
                        .HasFilter("IsActive = 1");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("Spellbox.Model.DeckZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "ZoneType")
                        .IsUnique();

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionAllocation", b =>
                {
                    b.HasOne("Spellbox.Model.CollectionBinder", null)
                        .WithMany()
                        .HasForeignKey("BinderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Spellbox.Model.CollectionBinder", null)
                        .WithMany("Cards")
                        .HasForeignKey("CollectionBinderId");

                    b.HasOne("Spellbox.Model.CollectionCard", "CollectionCard")
                        .WithMany("Allocations")
                        .HasForeignKey("CollectionCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spellbox.Model.DeckSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CollectionCard");
                });

            modelBuilder.Entity("Spellbox.Model.DeckCard", b =>
                {
                    b.HasOne("Spellbox.Model.DeckZone", "Zone")
                        .WithMany("Cards")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Spellbox.Model.DeckSnapshot", b =>
                {
                    b.HasOne("Spellbox.Model.Deck", "Deck")
                        .WithMany("Snapshots")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Spellbox.Model.DeckZone", b =>
                {
                    b.HasOne("Spellbox.Model.DeckSnapshot", "Snapshot")
                        .WithMany("Zones")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionBinder", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Spellbox.Model.CollectionCard", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("Spellbox.Model.Deck", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Spellbox.Model.DeckSnapshot", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Spellbox.Model.DeckZone", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
