// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spellbox.Contexts;

#nullable disable

namespace Spellbox.Migrations.OracleDb
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20260301215112_Symbology")]
    partial class Symbology
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4");

            modelBuilder.Entity("Spellbox.Model.CardFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Defense")
                        .HasColumnType("TEXT");

                    b.Property<string>("Loyalty")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManaCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleText")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Power")
                        .HasColumnType("TEXT");

                    b.Property<string>("Toughness")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OracleId");

                    b.HasIndex("OracleId", "Order")
                        .IsUnique();

                    b.ToTable("Faces");
                });

            modelBuilder.Entity("Spellbox.Model.CardOracle", b =>
                {
                    b.Property<Guid>("OracleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CMC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OracleId");

                    b.HasIndex("Name");

                    b.ToTable("Oracles");
                });

            modelBuilder.Entity("Spellbox.Model.CardVariant", b =>
                {
                    b.Property<Guid>("ScryfallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CardMarketProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Finishes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorTexts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Released")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScryfallId");

                    b.HasIndex("CardMarketProductId");

                    b.HasIndex("OracleId");

                    b.HasIndex("SearchName");

                    b.HasIndex("SetCode", "CollNum")
                        .IsUnique();

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("Spellbox.Model.Symbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SvgData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("Spellbox.Services.ScryfallSyncState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("Spellbox.Model.CardFace", b =>
                {
                    b.HasOne("Spellbox.Model.CardOracle", "Oracle")
                        .WithMany("Faces")
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oracle");
                });

            modelBuilder.Entity("Spellbox.Model.CardVariant", b =>
                {
                    b.HasOne("Spellbox.Model.CardOracle", "Oracle")
                        .WithMany("Variants")
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oracle");
                });

            modelBuilder.Entity("Spellbox.Model.CardOracle", b =>
                {
                    b.Navigation("Faces");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
