// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spellbox.Model;

#nullable disable

namespace Spellbox.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20260101041306_202601010509_Init")]
    partial class _202601010509_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4");

            modelBuilder.Entity("Spellbox.Model.CFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Defense")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManaCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleText")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Power")
                        .HasColumnType("TEXT");

                    b.Property<string>("Toughness")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OracleId", "Order")
                        .IsUnique();

                    b.ToTable("CardFaces");
                });

            modelBuilder.Entity("Spellbox.Model.CVariant", b =>
                {
                    b.Property<Guid>("ScryfallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Finishes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorTexts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OracleCardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Released")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScryfallId");

                    b.HasIndex("OracleCardId");

                    b.ToTable("CardVariants");
                });

            modelBuilder.Entity("Spellbox.Model.OracleCard", b =>
                {
                    b.Property<Guid>("OracleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CMC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OracleId");

                    b.ToTable("OracleCards");
                });

            modelBuilder.Entity("Spellbox.Model.CFace", b =>
                {
                    b.HasOne("Spellbox.Model.OracleCard", "OracleCard")
                        .WithMany("Faces")
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OracleCard");
                });

            modelBuilder.Entity("Spellbox.Model.CVariant", b =>
                {
                    b.HasOne("Spellbox.Model.OracleCard", "OracleCard")
                        .WithMany("Variants")
                        .HasForeignKey("OracleCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OracleCard");
                });

            modelBuilder.Entity("Spellbox.Model.OracleCard", b =>
                {
                    b.Navigation("Faces");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
