// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spellbox.Model;

#nullable disable

namespace Spellbox.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4");

            modelBuilder.Entity("Spellbox.Model.CardFace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Defense")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManaCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleText")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Power")
                        .HasColumnType("TEXT");

                    b.Property<string>("Toughness")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CardFaces");
                });

            modelBuilder.Entity("Spellbox.Model.CardLegality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commander")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explorer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Future")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gladiator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Historic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Legacy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modern")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oathbreaker")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oldschool")
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pauper")
                        .HasColumnType("TEXT");

                    b.Property<string>("PauperCommander")
                        .HasColumnType("TEXT");

                    b.Property<string>("Penny")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pioneer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Predh")
                        .HasColumnType("TEXT");

                    b.Property<string>("Premodern")
                        .HasColumnType("TEXT");

                    b.Property<string>("Standard")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeless")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vintage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CardLegalities");
                });

            modelBuilder.Entity("Spellbox.Model.CardVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Finishes")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorNames")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorTexts")
                        .HasColumnType("TEXT");

                    b.Property<string>("Images")
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Released")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbs")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CardVariants");
                });

            modelBuilder.Entity("Spellbox.Model.OracleCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CMC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorIdentity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OracleCards");
                });
#pragma warning restore 612, 618
        }
    }
}
